### ISSUE TITLE
Optionally start the kernel with a trusted sandbox

### ISSUE THREAD

**Issue by mpcjanssen** [rmculpepper/iracket#13]
I use Jupyter as my REPL of choice running om my local machine. In this case the current sandbox configuration (especially `sandbox-security-guard`) is too limited. For example, network requests are not allowed.
Would it be possible to add an argument while starting the kernel to start a trusted sandbox instead?

**Comment by gussmith23** [comment]
I see that this was closed, but how do I actually use the new flag? Sorry, completely new to Racket and Jupyter Notebook!

**Comment by mpcjanssen** [comment]
@gussmith23 you pass the -t parameter from `kernel.json`. What I do is 
- Install IRacket
- Make a copy of the IRacket kernel folder
- Add the `-t` parameter to `kernel.json`

My `kernel.json` is:

```json
{"argv":["racket","-l","iracket/iracket","--","-t","{connection_file}"],"display_name":"Racket (trusted)","language":"racket"}
```

**Comment by gussmith23** [comment]
Ah, thanks. I had done the same thing, but assumed there was a smoother way to do this! Thanks for the info.

**Comment by gussmith23** [comment]
I guess were I (or someone else) motivated, this could probably be implemented as a flag on the installation script...?
