### ISSUE TITLE
Question: where does the `make-header` come from?

### ISSUE THREAD

**Issue by lihebi** [rmculpepper/iracket#22]
Hi,

This is a question rather than issue.

Could you help me point out where does the `make-header` come from? It was used twice, but I didn't find where it is defined/imported.

https://github.com/rmculpepper/iracket/blob/9af0e87d61565a9ecb41119c481e7e36c0c5287d/private/jupyter.rkt#L33-L38

**Comment by rmculpepper** [comment]
It's defined later in the same file by `(define-struct/contract header ___)`.

**Comment by lihebi** [comment]
Ah, yes, thanks!! I kind-of forgot that the `define-struct` syntax automatically defines `make-XXX`.
